# Generated by Django 4.0.6 on 2022-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsrecord',
            name='is_spent',
            field=models.BooleanField(default=False),
        ),
    ]
